//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagement_Context : DbContext
    {
        public HotelManagement_Context()
            : base("name=HotelManagement_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblAddresstype> tblAddresstypes { get; set; }
        public virtual DbSet<tblcollection> tblcollections { get; set; }
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tblemployee> tblemployees { get; set; }
        public virtual DbSet<tblgender> tblgenders { get; set; }
        public virtual DbSet<tblinventory> tblinventories { get; set; }
        public virtual DbSet<tblinvoice> tblinvoices { get; set; }
        public virtual DbSet<tblmenuitem> tblmenuitems { get; set; }
        public virtual DbSet<tblorderdelivery> tblorderdeliveries { get; set; }
        public virtual DbSet<tblorder> tblorders { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
    }
}
