//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinventory
    {
        public int id { get; set; }
        public int quantity { get; set; }
        public string units { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> customerid { get; set; }
        public string Name { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
    
        public virtual tblcustomer tblcustomer { get; set; }
        public virtual tblproduct tblproduct { get; set; }
    }
}
