//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcollection
    {
        public int id { get; set; }
        public Nullable<int> invoiceid { get; set; }
        public Nullable<decimal> collectionamount { get; set; }
        public Nullable<decimal> pendingamount { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
    
        public virtual tblinvoice tblinvoice { get; set; }
    }
}
