//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public int id { get; set; }
        public string aadharnumber { get; set; }
        public decimal salary { get; set; }
        public Nullable<System.DateTime> joiningdate { get; set; }
        public Nullable<int> genderid { get; set; }
        public Nullable<int> addressid { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<int> customerid { get; set; }
        public string Name { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblcustomer tblcustomer { get; set; }
        public virtual tblgender tblgender { get; set; }
        public virtual tblrole tblrole { get; set; }
    }
}
